[tool.poetry]
name = "mutagen"
version = "1.47.1"
description = "read and write audio tags for many formats"
authors = []

[tool.poetry.dependencies]
python = "^3.8.1"
python-afl = {version = "^0.7.3", optional = true}

[tool.poetry.extras]
fuzzing-dev = ["python-afl"]

[tool.poetry.dev-dependencies]
pytest = "^7.1.2"
hypothesis = "^6.50.1"
flake8 = "^6.1.0"
mypy = "1.5.1"
coverage = "^7.2.5"
Sphinx = "^6.2.1"
sphinx-rtd-theme = "^1.0.0"
sphinx-autobuild = "^2021.3.14"
setuptools = "^68.1.2"

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.coverage.run]
include=["mutagen/*", "tests/*"]
